version: 0.4.{build}
configuration: Release
image: Visual Studio 2019
platform: x86
clone_depth: 2
clone_folder: C:\lua-openssl
install:
- cd c:\lua-openssl
- git submodule update --init --recursive
- git submodule update --recursive
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
- ls C:\openssl-v111-win32\lib
- cd C:\
- git clone http://luajit.org/git/luajit-2.0.git C:\luajit-2.0
build_script:
- cd c:\luajit-2.0\src
- msvcbuild.bat
- copy luajit.exe C:\
- copy lua51.* C:\
- cd c:\lua-openssl
- nmake -f makefile.win
- copy src\openssl.dll c:\
test_script:
- cd test\
- set LUA_PATH=?.lua;
- set LUA_CPATH=C:\?.dll;
- c:\luajit.exe test.lua
