name: CI

on: [push, pull_request]

jobs:
  bindings-coverage:
    runs-on: ubuntu-latest
    env:
      LUA: luajit2.1
      LUAROCKS: ""
      COVERALLS_GIT_BRANCH: "${{ github.ref }}"
      COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: cpp-coveralls
      run: pip install cpp-coveralls PyYAML
    - name: openssl
      run: sudo apt install libssl-dev -y
    - name: luajit2
      run: .github/shell/setup_lua.sh
    - name: run
      run: PKG_CONFIG_PATH=$HOME/.usr/lib/pkgconfig PATH=$HOME/.usr/bin:$PATH LD_LIBRARY_PATH=$HOME/.usr/lib make coveralls

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        luarocks_version: [2.4.4]
        #luarocks_version: [2.4.4, 3.7.0]
        lua_version: [luajit2.1]
        #openssl_version: [openssl-1.0.2u, libressl-3.2.5, openssl-1.1.1j]
        openssl_version: [openssl-1.0.2u, openssl-1.1.1j]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12
      LUAROCKS: ${{ matrix.luarocks_version }}
      LUA: ${{ matrix.lua_version }}
      SSL: ${{ matrix.openssl_version }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup
      run:
        .github/shell/setup_lua.sh && .github/shell/setup_ssl.sh

    - name: Build
      run:
        .github/shell/build.sh

    - name: Test
      run:
        PKG_CONFIG_PATH=$HOME/.usr/lib/pkgconfig PATH=$HOME/.usr/bin:$PATH LD_LIBRARY_PATH=$HOME/.usr/lib make test

